name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    env:
      build_type: "Release"
      vulkan_version: "1.2.162.1"
      vulkan_sdk: "/Volumes/vulkansdk-macos-1.2.162.1"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "macOS 10.15 + Xcode 11.7"
            os: macos-10.15
            compiler: xcode
            version: "11.7"
          - name: "macOS 10.15 + Xcode 12.2"
            os: macos-10.15
            compiler: xcode
            version: "12.2"

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Vulkan SDK
      run: |
        # Download Vulkan SDK
        curl -LS -o vulkansdk.dmg \
          https://sdk.lunarg.com/sdk/download/${{ env.vulkan_version }}/mac/vulkansdk-macos-${{ env.vulkan_version }}.dmg
        # Create Vulkan SDK directory and extract
        hdiutil attach vulkansdk.dmg
    - name: Configure CMake
      shell: bash
      run: |
        ls -ls /Applications/
        sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "VULKAN_SDK=${{ env.vulkan_sdk }}/macOS" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=${{ env.vulkan_sdk }}/macOS/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "VK_ICD_FILENAMES=${{ env.vulkan_sdk }}/macOS/etc/vulkan/icd.d/MoltenVK_icd.json" >> $GITHUB_ENV
        echo "${{ env.vulkan_sdk }}/macOS/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${{ env.vulkan_sdk }}/macOS/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Configure Build
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.build_type}}
    - name: Build
      run: cd build && make
    - name: Run Unit Test
      run: /Users/runner/work/YachtSimulator/YachtSimulator/build/bin/UnitTests