name: Window

on:
  push:
    branches: [ main, refactor ]
  pull_request:
    branches: [ main ]

jobs:
  build-window:
    env:
      build_type: "Release"
      vulkan_sdk: "C:/VulkanSDK"
      vulkan_version: "1.2.162.1"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows Server 2019 + Visual Studio 2019"
            os: windows-2019

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Vulkan SDK
      run: |
        choco install --yes vulkan-sdk --version=${{env.vulkan_version}}
    - name: Configure CMake
      shell: bash
      run: |
        echo "VULKAN_SDK=${{ env.vulkan_sdk }}/${{ env.vulkan_version }}" >> $GITHUB_ENV
        echo "VK_SDK_PATH=${{ env.vulkan_sdk }}/${{ env.vulkan_version }}" >> $GITHUB_ENV
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=${{env.build_type}} ..
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: cd build && MSBuild.exe YachtSimulator.sln /p:Configuration=${{env.build_type}}
    - name: Run Unit Test
      run: /a/YachtSimulator/YachtSimulator/build/bin/${{env.build_type}}/UnitTests.exe